"""added indexes to db

Revision ID: 08b766467980
Revises: 86d0ad95fa42
Create Date: 2026-02-27 22:50:34.513185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b766467980'
down_revision: Union[str, Sequence[str], None] = '86d0ad95fa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_match_competition_id', 'match', ['competition_id'], unique=False)
    op.create_index('ix_match_utc_date', 'match', ['utc_date'], unique=False)
    op.create_index('ix_review_match_id', 'review', ['match_id'], unique=False)
    op.create_index('ix_review_user_id', 'review', ['user_id'], unique=False)
    op.create_index('ix_tag_player_id', 'reviewplayertag', ['player_id'], unique=False)
    op.create_index('ix_tag_review_id', 'reviewplayertag', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_review_id', table_name='reviewplayertag')
    op.drop_index('ix_tag_player_id', table_name='reviewplayertag')
    op.drop_index('ix_review_user_id', table_name='review')
    op.drop_index('ix_review_match_id', table_name='review')
    op.drop_index('ix_match_utc_date', table_name='match')
    op.drop_index('ix_match_competition_id', table_name='match')
    # ### end Alembic commands ###
