"""added unique review constraint

Revision ID: 86d0ad95fa42
Revises: 8b34fd94ac7e
Create Date: 2026-02-15 15:10:02.119241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d0ad95fa42'
down_revision: Union[str, Sequence[str], None] = '8b34fd94ac7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'review', ['user_id', 'match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='unique')
    # ### end Alembic commands ###
